/*
 * StartFrame.java
 *
 * Created on 7. Juli 2008, 16:30
 */


package metamindmachine;


import java.awt.*;
import java.io.*;
import java.util.*;


/**
 *
 * @author  rain
 */
public class StartFrame extends javax.swing.JFrame {


    String[] seqlistfile = new String[100];
    String[] seqlistname = new String[100];
    int seqlistnum=0;
    
    private Object makeObj(final String item) {
        return new Object() { public String toString() { return item; } };
    }
    
    /** Creates new form StartFrame */
    public StartFrame() {
        initComponents();
        
        setTitle("MetaMindMachine binaural Brainwave Lab v0.1b");
        //setSize(640, 480);
        
        Toolkit toolkit = Toolkit.getDefaultToolkit();  
        Dimension sSize = toolkit.getScreenSize();  
        int x = (sSize.width - getWidth()) / 2;  
        int y = (sSize.height - getHeight()) / 2;  
        setLocation(x, y);          
        
        //fill Combobox with available sequences
        File path = new File(Main.sequencedir);
        File files[] = path.listFiles();
        Arrays.sort(files);
        String namestr=null;
        
        for(int fi=0;fi < files.length;fi++) {
            String fstr = files[fi].toString();
            if(fstr.substring(fstr.length()-5,fstr.length()).contains(".mmms") != false) {
                
                int start = fstr.indexOf('/');
                if(start != -1) {
                    namestr = fstr.substring(start+1, fstr.length()-5);
                }
                start = fstr.indexOf('_');
                if(start != -1) {
                    namestr = fstr.substring(start+1, fstr.length()-5);
                }
                seqlistfile[seqlistnum] = fstr;
                seqlistname[seqlistnum] = namestr;
                //System.out.println(seqlistname[seqlistnum]);
                SequenceSelector.addItem(makeObj(namestr));
                seqlistnum++;

            }
                
        }
        
        
        setVisible(true);
        getContentPane().setBackground(new Color(111,111,111));
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartButton = new javax.swing.JButton();
        GraphPanel = new SequenceGraph();
        SequenceSelector = new javax.swing.JComboBox();
        BrainwaveLabel = new javax.swing.JLabel();
        lengthLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setBounds(new java.awt.Rectangle(0, 0, 640, 480));
        setMinimumSize(new java.awt.Dimension(640, 480));

        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        GraphPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout GraphPanelLayout = new javax.swing.GroupLayout(GraphPanel);
        GraphPanel.setLayout(GraphPanelLayout);
        GraphPanelLayout.setHorizontalGroup(
            GraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        GraphPanelLayout.setVerticalGroup(
            GraphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 304, Short.MAX_VALUE)
        );

        SequenceSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SequenceSelectorActionPerformed(evt);
            }
        });

        BrainwaveLabel.setText("Brainwave sequence:");

        lengthLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(GraphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(BrainwaveLabel)
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lengthLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SequenceSelector, javax.swing.GroupLayout.Alignment.LEADING, 0, 227, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SequenceSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BrainwaveLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lengthLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(GraphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StartButton)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        // TODO add your handling code here:
        Main.status = 2;
    }//GEN-LAST:event_StartButtonActionPerformed

    
    private void SequenceSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SequenceSelectorActionPerformed
        String estr = evt.toString();
        String sname=null;
        
        //System.out.println(evt);
        //if(estr.indexOf("modifiers=Button1") == -1) return;
        int start = estr.indexOf("selectedItemReminder=");
        int end = estr.indexOf(']');
        if(start != -1 && end != -1) {
            sname = estr.substring(start+21,estr.length()-1);
            
            //System.out.println(sname);
            for(int i=0;i < SequenceSelector.getItemCount();i++) {
                if(sname.equals(SequenceSelector.getItemAt(i).toString())) {
                    System.out.println("sequence file "+i+" load: "+seqlistfile[i]);
                    Main.sessionmgr.sequence.LoadSequence(seqlistfile[i]);
                    String lengthstr = "Length: "+Main.sessionmgr.sequence.length / 60 +":"+Main.sessionmgr.sequence.length % 60 + " minutes";
                    lengthLabel.setText(lengthstr);
                }
            }            
            
            GraphPanel.repaint();
        }

    }//GEN-LAST:event_SequenceSelectorActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BrainwaveLabel;
    public javax.swing.JPanel GraphPanel;
    private javax.swing.JComboBox SequenceSelector;
    private javax.swing.JButton StartButton;
    private javax.swing.JLabel lengthLabel;
    // End of variables declaration//GEN-END:variables
    
}


